### ISSUE TITLE
Can't build npm pack with ng-packagr

### ISSUE THREAD

**Issue by benshabatnoam** [taldor-ltd/angular-grid-cell#18]
In version 2.0.0 we can't create npm pack with ng-packagr.

The given error:
BUILD ERROR
```
src/app/grid-cell/components/elements/text-element/classes/text-element.ts(1,25): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/text-element/classes/text-element.ts(8,10): error TS2339: Property 'field' does not exist on type 'TextElement'.
src/app/grid-cell/components/elements/text-element/text-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
src/app/grid-cell/components/elements/button-element/classes/button-element.ts(1,25): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/button-element/button-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
src/app/grid-cell/components/elements/image-element/classes/image-element-base.ts(1,25): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/image-element/image-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
src/app/grid-cell/components/elements/icon-element/classes/icon-element-base.ts(1,25): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/icon-element/icon-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
src/app/grid-cell/components/elements/date-time-element/classes/date-time-element-base.ts(1,25): error TS2307: Cannot find
module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/date-time-element/classes/date-time-element.ts(1,28): error TS2307: Cannot find module 'src/app/grid-cell/models/enums/moment-pipe.enum'.
src/app/grid-cell/components/elements/date-time-element/date-time-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
: Can't bind to 'data' since it isn't a known property of 'tld-date-time-element'.
1. If 'tld-date-time-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-date-time-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("type">
      <span *ngSwitchCase="'datetime'">
        <tld-date-time-element [element]="element" [ERROR ->][data]="data"></tld-date-time-element>
      </span>
      <span *ngSwitchCase="'icon'">
")
: Can't bind to 'data' since it isn't a known property of 'tld-icon-element'.
1. If 'tld-icon-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-icon-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component
to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      </span>
      <span *ngSwitchCase="'icon'">
        <tld-icon-element [element]="element" [ERROR ->][data]="data"></tld-icon-element>
      </span>
      <span *ngSwitchCase="'image'">
")
: Can't bind to 'data' since it isn't a known property of 'tld-image-element'.
1. If 'tld-image-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-image-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("      </span>
      <span *ngSwitchCase="'image'">
        <tld-image-element [element]="element" [ERROR ->][data]="data"></tld-image-element>
      </span>
      <span *ngSwitchCase="'text'">
")
: Can't bind to 'data' since it isn't a known property of 'tld-text-element'.
1. If 'tld-text-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-text-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component
to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      </span>
      <span *ngSwitchCase="'text'">
        <tld-text-element [element]="element" [ERROR ->][data]="data"></tld-text-element>
      </span>
      <span *ngSwitchCase="'button'">
")
: Can't bind to 'data' since it isn't a known property of 'tld-button-element'.
1. If 'tld-button-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-button-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("    </span>
      <span *ngSwitchCase="'button'">
        <tld-button-element [element]="element" [ERROR ->][data]="data"></tld-button-element>
      </span>
    </span>
")

Error: src/app/grid-cell/components/elements/text-element/classes/text-element.ts(1,25): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/text-element/classes/text-element.ts(8,10): error TS2339: Property 'field' does not exist on type 'TextElement'.
src/app/grid-cell/components/elements/text-element/text-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
src/app/grid-cell/components/elements/button-element/classes/button-element.ts(1,25): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/button-element/button-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
src/app/grid-cell/components/elements/image-element/classes/image-element-base.ts(1,25): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/image-element/image-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
src/app/grid-cell/components/elements/icon-element/classes/icon-element-base.ts(1,25): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/icon-element/icon-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
src/app/grid-cell/components/elements/date-time-element/classes/date-time-element-base.ts(1,25): error TS2307: Cannot find
module 'src/app/grid-cell/models/classes/element'.
src/app/grid-cell/components/elements/date-time-element/classes/date-time-element.ts(1,28): error TS2307: Cannot find module 'src/app/grid-cell/models/enums/moment-pipe.enum'.
src/app/grid-cell/components/elements/date-time-element/date-time-element.component.ts(2,38): error TS2307: Cannot find module 'src/app/grid-cell/models/classes/base-element-component'.
: Can't bind to 'data' since it isn't a known property of 'tld-date-time-element'.
1. If 'tld-date-time-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-date-time-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("type">
      <span *ngSwitchCase="'datetime'">
        <tld-date-time-element [element]="element" [ERROR ->][data]="data"></tld-date-time-element>
      </span>
      <span *ngSwitchCase="'icon'">
")
: Can't bind to 'data' since it isn't a known property of 'tld-icon-element'.
1. If 'tld-icon-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-icon-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component
to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      </span>
      <span *ngSwitchCase="'icon'">
        <tld-icon-element [element]="element" [ERROR ->][data]="data"></tld-icon-element>
      </span>
      <span *ngSwitchCase="'image'">
")
: Can't bind to 'data' since it isn't a known property of 'tld-image-element'.
1. If 'tld-image-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-image-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("      </span>
      <span *ngSwitchCase="'image'">
        <tld-image-element [element]="element" [ERROR ->][data]="data"></tld-image-element>
      </span>
      <span *ngSwitchCase="'text'">
")
: Can't bind to 'data' since it isn't a known property of 'tld-text-element'.
1. If 'tld-text-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-text-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component
to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      </span>
      <span *ngSwitchCase="'text'">
        <tld-text-element [element]="element" [ERROR ->][data]="data"></tld-text-element>
      </span>
      <span *ngSwitchCase="'button'">
")
: Can't bind to 'data' since it isn't a known property of 'tld-button-element'.
1. If 'tld-button-element' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'tld-button-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("    </span>
      <span *ngSwitchCase="'button'">
        <tld-button-element [element]="element" [ERROR ->][data]="data"></tld-button-element>
      </span>
    </span>
")
    at Object.<anonymous> (c:\noamb\Projects\angular-grid-cell\modules\angular-grid-cell\node_modules\ng-packagr\lib\ngc\compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (c:\noamb\Projects\angular-grid-cell\modules\angular-grid-cell\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
    at <anonymous>
```

**Comment by benshabatnoam** [comment]
In last commit (2456fbd2211f25d75807aa0bd793a6f00f79a8b4) I've removed `@Input` properties in `base-element-component`.
It turns out that angular don't like `@Input` properties in derived classes.
So, I changed this properties to regular properties, so that the `base-element-component` class's code will know theme, and moved the `@Input` properties to the components.

**Comment by oferah** [comment]
> It turns out that angular don't like `@Input` properties in derived classes.

This is incorrect. This commit (604275d96c0d543e94420b44696583fbd59868a4) includes `@Input` properties in base class and there is no error.
